index=* sourcetype="docker:json"
| rex field=line "^(?<client_ip>\d+\.\d+\.\d+\.\d+)"
| rex field=line "\"\w+\s+(?<uri>\S+)\s+HTTP"
| eval uri_decoded = urldecode(uri)
| where match(uri_decoded, "(?i)<script|alert|select|union|--|\.\.\/|url=http|whoami|ls|<!ENTITY")
| stats min(_time) as start_time, max(_time) as end_time by client_ip
| eval duration = end_time - start_time
| where duration >= 0
| stats avg(duration) as mttr
| eval mttr = if(mttr < 1, "< 1", round(mttr / 60, 2)) . " dəqiqə"
