index=* sourcetype="docker:json"
| rex field=line "^(?<client_ip>\d+\.\d+\.\d+\.\d+)\s+-\s+-\s+\[[^\]]+\]\s+\"\w+\s+(?<uri>\S+)\s+HTTP"
| eval uri_decoded = urldecode(uri)
| where match(uri_decoded, "(?i)(http|https|ftp):\/\/") AND NOT match(uri_decoded, "baydirman\.site")
| table _time, client_ip, uri_decoded
